version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 8080:80
  server:
    build: ./server
    command: yarn start
    environment:
      - TYPEORM_HOST=db
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redispass
    depends_on:
      - db
      - redis
    ports:
      - 3030:3030
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
    volumes:
      - ./server/data:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
