apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: chainlink-production-

commonLabels:
  environment: production
  app: chainlink

resources:
- ../../bases/base

vars:
  - fieldref:
      fieldpath: metadata.labels.image_tag
    name: TAG
    objref:
      name: client
      apiVersion: apps/v1
      kind: Deployment
  - fieldref:
      fieldpath: metadata.labels.image_tag
    name: TAG
    objref:
      name: server
      apiVersion: apps/v1
      kind: Deployment


# configMapGenerator:
#   - name: config-server
#     literals:
#     - 