apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: chainlink-production-

commonLabels:
  environment: production
  app: chainlink

resources:
- ../../bases/base

secretGenerator:
  - name: secrets
    envs: 
    - secrets-gen.env
    type: Opaque

# configMapGenerator:
#   - name: client-config
#     envs:
#     - client-config-gen.env
