env:
  branch: ${{ github.head_ref || github.ref_name }} 

name: 🏢 Build & Push Server
on: 
  push:
    paths:
    - 'server/**'
    - 'kube/bases/server/**'
    branches:
    - main
  pull_request:
    paths:
    - 'server/**'
    - 'kube/bases/server/**'
    branches:
    - main
    - 'releases/**'
# All jobs run on different VM's, so we do have to repeat some things here.
jobs:
  Build_Server:
    name: Build_Server
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Docker Buildx action
        id: buildx
        uses: docker/setup-buildx-action@v1.7.0
        with:
          version: latest
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

      - name: Build and Push Server
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/chainlink-server:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/chainlink-server:${{ runner.os }}-${{ github.run_number }}
          secrets: GIT_AUTH_TOKEN=${{ github.token }}
