apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: client

resources:
- service.yaml
- deployment.yaml

vars:
  - fieldref:
      fieldpath: metadata.labels.image_tag
    name: TAG
    objref:
      name: client
      apiVersion: apps/v1
      kind: Deployment