
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    component: client
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    targetPort: 80
  selector:
    component: client