
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    component: client
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: http
  selector:
    component: client