
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    component: client
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    component: client