apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    component: server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: # Below settings are not ideal for real production app.
      maxUnavailable: 50%
      maxSurge: 100%
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      serviceAccountName: server
      containers:
        - name: server
          image: s1dequest/chainlink-server:latest
          command: ["yarn", "start"]
          envFrom:
            - secretRef:
                name: secrets # Patched in at overlay level. Created by temp file at deploy.
          ports:
            - name: listen
              containerPort: 3030  # Available to all other nodes on the cluster, but does not use 3030 on the actual nodes.
          resources:
            requests:
              memory: "1gb"
              cpu: "0.25"
            limits:
              memory: "1gb"
              cpu: "0.25"
          # ADD LIVENESS/READINESS PROBES
          lifecycle:
            preStop:
              # pause for 10 seconds before shutdown to handle any stray traffic
              exec:
                command: ["/bin/sleep", "10"]