
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    component: server
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: server
    targetPort: 80
  selector:
    component: server