env:
  branch: ${{ github.head_ref || github.ref_name }} 

name: 🚢 Client Build & Push
on: 
  push:
    paths:
    - 'client/**'
    branches:
    - main
  pull_request:
    paths:
    - 'client/**'
    branches:
    - main
    - 'releases/**'
jobs:
  Client:
    runs-on: ubuntu-20.04
    needs: Setup
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            ${{ secrets.AWS_ECR_URL }}:latest
            ${{ secrets.AWS_ECR_URL }}:${{ runner.os }}-${{ github.run_number }}
          secrets: GIT_AUTH_TOKEN=${{ github.token }}
