env:
  branch: ${{ github.head_ref || github.ref_name }} 

name: 🚢 Server Build & Push
on: 
  push:
    paths:
    - 'server/**'
    branches:
    - main
  pull_request:
    paths:
    - 'server/**'
    branches:
    - main
    - 'releases/**'
jobs:
  Server:
    runs-on: ubuntu-20.04
    needs: Setup
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ secrets.AWS_ECR_URL }}:latest
            ${{ secrets.AWS_ECR_URL }}:${{ runner.os }}-${{ github.run_number }}
          secrets: GIT_AUTH_TOKEN=${{ github.token }}

# IDEA
# Only build and push images when files in those folders have been altered.
# Only deploy to staging if a label has been added - 'Stage'
# For deploys, define job dependencies: https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow