name: build
on: 
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches:
      - main
      - 'releases/**'
jobs:
  build:
    env:
      ECR_REPO: example.com
    runs-on: ubuntu-20.04
    steps:
      - id: build
        run: ./.github/scripts/build.sh
