env:
  branch: ${{ github.head_ref || github.ref_name }} 

name: 🚢 Client Build & Push
on: 
  push:
    paths:
    - 'client/**'
    branches:
    - main
  pull_request:
    paths:
    - 'client/**'
    branches:
    - main
    - 'releases/**'
jobs:
  Build_Server:
    runs-on: ubuntu-20.04
    env:
      ECR_REPO: example.com
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2.4.2
      
      - name: Setup Docker Buildx action
        id: buildx
        uses: docker/setup-buildx-action@v1.7.0
        with:
          version: latest
      
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AWS_ECR_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_ACCESS_KEY }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            ${{ secrets.AWS_ECR_URL }}:latest
            ${{ secrets.AWS_ECR_URL }}:${{ runner.os }}-${{ github.run_number }}
          secrets: GIT_AUTH_TOKEN=${{ github.token }}
