env:
  branch: ${{ github.head_ref || github.ref_name }}
  ENV: production
  APP: chainlink

name: 🧱 Prod CI/CD Pipeline
on: 
  push:
    # paths:
    # - 'server/**'
    # - 'client/**'
    # - 'kube/**'
    branches:
    - main
# All jobs run on different VM's, so we do have to repeat some things here.
jobs:
  Build_Images:
    name: 🏢 Build & Push Images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Docker Buildx action
        id: buildx
        uses: docker/setup-buildx-action@v1.7.0
        with:
          version: latest
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

      - name: Build and Push Server
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}-server:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}-server:${{ runner.os }}-${{ github.run_number }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}-server:${{ runner.os }}-${{ github.sha }}
          secrets: GIT_AUTH_TOKEN=${{ github.token }}
      
      - name: Build and Push client
        id: docker_build_client
        uses: docker/build-push-action@v3
        env:
          REACT_APP_BACKEND_URL: server
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}-client:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}-client:${{ runner.os }}-${{ github.run_number }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}-client:${{ runner.os }}-${{ github.sha }}
          secrets: GIT_AUTH_TOKEN=${{ github.token }}
  Deploy_App:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-20.04
    needs: [ Build_Images ]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2.4.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Run Deploy Script
        id: deploy_app
        env:
          IMAGE_REPO_SERVER: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}-server
          IMAGE_REPO_CLIENT: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}-client
          IMAGE_TAG: ${{ runner.os }}-${{ github.sha }}
          DEPLOY_RELEASE: ${{ env.APP }}-${{ env.ENV }}
          ENV: ${{ env.ENV }}
          APP: ${{ env.APP }}
          RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
          RDS_PW: ${{ secrets.RDS_PW }}
          RDS_UN: ${{ secrets.RDS_UN }}
          ELASTICACHE_ENDPOINT: ${{ secrets.ELASTICACHE_ENDPOINT }}
          REACT_BACKEND_URL: server
        run: |
          bash .github/scripts/deploy.sh

      - name: Monitor and Rollback on Error
        id: monitor_and_rollback
        env:
          ENV: ${{ env.ENV }}
        run: |
          bash .github/scripts/monitor.sh

