env:
  branch: ${{ github.head_ref || github.ref_name }} 

name: 🍣 Build & Push Redis
on: 
  push:
    paths:
    - 'redis/**'
    branches:
    - main
  pull_request:
    paths:
    - 'redis/**'
    branches:
    - main
    - 'releases/**'
# All jobs run on different VM's, so we do have to repeat some things here.
jobs:
  Redis:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Docker Buildx action
        id: buildx
        uses: docker/setup-buildx-action@v1.7.0
        with:
          version: latest
      
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AWS_ECR_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_ACCESS_KEY }}

      - name: Build and Push redis
        id: docker_build_redis
        uses: docker/build-push-action@v3
        with:
          context: ./redis
          file: ./redis/Dockerfile
          push: true
          tags: |
            ${{ secrets.AWS_ECR_URL }}/chainlink-redis:latest
            ${{ secrets.AWS_ECR_URL }}/chainlink-redis:${{ runner.os }}-${{ github.run_number }}
          secrets: GIT_AUTH_TOKEN=${{ github.token }}
