env:
  branch: ${{ github.head_ref || github.ref_name }} 

name: 🏗️ Pipeline Setup - Checkout Repo & Login to ECR
on: 
  push:
    paths:
    - 'client/**'
    - 'server/**'
    - 'redis/**'
    branches:
    - main
  pull_request:
    paths:
    - 'client/**'
    - 'server/**'
    - 'redis/**'
    branches:
    - main
    - 'releases/**'
jobs:
  Setup:
    runs-on: ubuntu-20.04
    env:
      ECR_REPO: example.com # Just putting this here as a reference for later env var population.
    steps:       
      - name: Setup Docker Buildx action
        id: buildx
        uses: docker/setup-buildx-action@v1.7.0
        with:
          version: latest
      
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AWS_ECR_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_ACCESS_KEY }}